version: '3'

services:
  db_api:
    container_name: backend_postgres_api
    image: postgres:16
    environment:
      POSTGRES_DB: "ApiDataBase"
      POSTGRES_USER: "postgres_api"
      POSTGRES_PASSWORD: "postgres_api"
    volumes:
      - api_data:/var/lib/postgresql/data
    restart: always
    networks:
      - SuperDuperNetwork

  db_socket:
    container_name: backend_postgres_socket
    image: postgres:16
    environment:
      POSTGRES_DB: "SocketDataBase"
      POSTGRES_USER: "postgres_socket"
      POSTGRES_PASSWORD: "postgres_socket"
    volumes:
      - socket_data:/var/lib/postgresql/data
    restart: always
    networks:
      - SuperDuperNetwork

  redis:
    container_name: backend_redis
    image: redis:7
    restart: always
    networks:
      - SuperDuperNetwork

  app_socket:
    container_name: backend_app_socket
    build: ../GroupProject/SocketComponent
    volumes:
      - socket_static_data:/var/www/socket/static/
      - socket_media_data:/var/www/socket/media/
    depends_on:
      - redis
      - db_socket
    restart: always
    networks:
      - SuperDuperNetwork

  app_api:
    container_name: backend_app_api
    build: ../GroupProject/ApiComponent
    volumes:
      - api_static_data:/var/www/api/static/
      - api_media_data:/var/www/api/media/
    depends_on:
      - redis
      - db_socket
    restart: always
    networks:
      - SuperDuperNetwork

  nginx:
    container_name: backend_nginx
    build: ../GroupProject/NginxComponent
    ports:
      - "8000:8000"
    volumes:
      - socket_static_data:/var/www/socket/static/
      - socket_media_data:/var/www/socket/media/
      - api_static_data:/var/www/api/static/
      - api_media_data:/var/www/api/media/
    depends_on:
      - app_socket
    restart: always
    networks:
      - SuperDuperNetwork

  frontend:
    build: .
    ports:
      - "8080:80"
    networks:
      - SuperDuperNetwork

volumes:
  api_data:
  socket_data:
  socket_static_data:
  socket_media_data:
  api_static_data:
  api_media_data:

networks:
  SuperDuperNetwork:
    driver: bridge